### ISSUE TITLE
Storybook InfoListItem Missing Color in Dev

### ISSUE THREAD

**Issue by emclaug2** [pxblue/react-component-library#104]
#### Describe the bug
The Storybook Dev environment's InfoListItem is missing an icon color.

#### What is the expected behavior?
The icon should be colored.

#### What are the steps to reproduce?
https://pxblue-components.github.io/react-dev/?path=/story/components-info-list-item--with-icon

The icon should be green.

The Material UI Stylesheets are being loaded in the incorrect order. 
Master does not have this issue, meaning something happened in dev that caused the ordering of the style sheets to change:
Primary suspects:
1. Webpack loader
2. Minor version of storybook update
3. Minor version of material-ui update? 

#### What is your environment?

 Framework
- [ ] Angular
- [x ] React
- [ ] Ionic
- [ ] React Native

 Browser
- [ ] Internet Explorer
- [ ] Edge
- [ ] Safari
- [ x] Chrome
- [ ] Firefox

 Operating System
- [x ] MacOS
- [x ] Windows
- [ ] Other

**Comment by emclaug2** [comment]
Did a fix for this get merged in?

**Comment by joebochill** [comment]
Should be fixed now
