### ISSUE TITLE
InfoListItem should be renderable as a link

### ISSUE THREAD

**Issue by joebochill** [pxblue/react-component-library#113]
#### Describe the desired behavior
I want to be able to right-click on an InfoListItem and choose "Open Link in a new Tab". In order to do this, we need to set the `component` prop of the ListItem to `Link` and supply an `href` prop to it. I propose we expose a `href` prop on the InfoListItem and then tweak the logic around the onClick event based on that.

#### Describe the current behavior
Can't open in a new tab because any navigation behavior is handled in javascript.

#### Is this request related to a current issue?
It's related to something I want to do for another project, but hasn't yet been an issue for any internal projects.

#### Additional Context
This may get fixed when we expose all of the MUI ListItem props on our InfoListItem. That should give an end user the ability to get the desired behavior, but we might still want to give them a shortcut-y way to do it.

**Comment by huayunh** [comment]
I wonder how this is going to perform on ionic if we do `Window.open()`?

**Comment by huayunh** [comment]
OK. According to my experiment on Docit, these are the four lines of code you can add to InfoListItem to turn it into something you want:

```tsx
<InfoListItem
   ...
   // @ts-ignore
   component={'a'}
   href={'ssdfsd'}
   button
/>
```
![image](https://user-images.githubusercontent.com/8997218/90453022-869b8000-e0bd-11ea-94e0-26f79d2f192f.png)

( I don't know why I need a ts-ignore here... are they turning `component` into their hidden API?)

----

If you want to use this somewhere in a pxblue drawer, I suppose we can tweak the drawer API a bit to pass in all the user-supplied info-list-item props, like this: 

```tsx
export type NavItem = {...} & PXBlueDrawerInheritableProperties & InfoListItemProps;
```

**Comment by joebochill** [comment]
I would like to shy away from using `component={'a'}` due to the fact that anchor links will cause the entire application to reload, whereas a `<Link>` from react-router-dom would do a 'soft' redirect without reloading the entire application.

The principle should be the same as with a.

**Comment by huayunh** [comment]
Closing this issue:

During our Office Hour discussion, we found that if you do this to the info list item, you will be able to route it nicely

```tsx

import { Link } from 'react-router-dom';

<InfoListItem
    ...
    // @ts-ignore
    component={Link}
    to={'/overview'}
    button
/>
```

But, like we mentioned above, we might want to be able to do that with our Drawer component too. Maybe use `Link` by default, but allow the users to pass in whatever `component` they would like to render it in.
