### ISSUE TITLE
ItemID marked as required in UserMenu menuGroups

### ISSUE THREAD

**Issue by joebochill** [pxblue/react-component-library#117]
#### Describe the bug
When using the UserMenu component, typescript complains that the property itemID (from DrawerNavItem) is required.

#### What is the expected behavior?
This property is not required in the UserMenu component.

#### Screenshots or links to minimum reproduction example
![image](https://user-images.githubusercontent.com/29152776/80377114-d208f480-8868-11ea-8450-5131f6710790.png)

**Comment by huayunh** [comment]
The item ID is used for the list key and identifying the current `activeItem`.  If the activeItem is not useful in the UserMenu context, we can have the component generating a few faked itemID for the user. 

I thought you are OOO this week. Was PXBlue this attractive to you?

**Comment by joebochill** [comment]
I was trying to use it in another project I'm working on this week...just consider me an outside collaborator :)

**Comment by huayunh** [comment]
Ok, thanks for following our contributing guideline :)
