### ISSUE TITLE
Consider refactoring the ScoreCard component

### ISSUE THREAD

**Issue by joebochill** [pxblue/react-component-library#149]
#### Describe the desired behavior
Might be nice to have the scorecard broken down into several smaller sub-components instead of using a function inside of the scorecard component to generate the different pieces.

#### Describe the current behavior
All of the sub-pieces are defined as functions inside of the ScoreCard through useCallback. 

#### Is this request related to a current issue?
No

#### Additional Context
You can look at how the Header was refactored in RN for an example of how this could be broken down/structured.

**Comment by huayunh** [comment]
Talk with the team about how to design API when creating the component

**Comment by jeffvg** [comment]
moved to PXBLUE-1914
