### ISSUE TITLE
Add props to handle test IDs

### ISSUE THREAD

**Issue by joebochill** [pxblue/react-component-library#15]
#### Describe the desired behavior
Add a prop for adding a data-test-id, e.g. `<Hero testID={'test'}/>`

#### Describe the current behavior
In order to place a test ID on a component, it has to be wrapped, which can break positioning, etc. When placing a test-id directly on a component, it gets ignored.

#### Is this request related to a current issue?
This is related to issues with the ScoreCard component in WAS

**Comment by huayunh** [comment]
Should we add a `PXBlueComponentProps` type that enforces the addition of `classes` and `testID` props to all our (future) components?

**Comment by joebochill** [comment]
> Should we add a `PXBlueComponentProps` type that enforces the addition of `classes` and `testID` props to all our (future) components?

Since the classes change for each component, I don't know that we can make a generic type to enforce it across all of our components.

**Comment by joebochill** [comment]
Looks like the work to extend the root component props has indeed given us the ability to add any `data-*` property we want onto the component when it's used in an application. So there is no need to add this prop to the components.
