### ISSUE TITLE
Undesired sticky scroll when navigating

### ISSUE THREAD

**Issue by joebochill** [pxblue/react-component-library#16]
#### Describe the bug
`DrawerLayout`
When navigating to a new page, the scroll position of the page is maintained instead of scrolling to the top of the content.

#### What is the expected behavior?
The default browser behavior should be maintained: scroll to top when visiting a new pages, restore the scroll position when using the back button.

#### What are the steps to reproduce?
1. Create an application with two routes and enough content on each to scroll (and buttons or links to navigate between them).
2. Scroll down on the first page and click the button to go to the second
3. Notice that the second page is scrolled down instead of being at the top of the content.

#### Screenshots or links to minimum reproduction example
You can see this behavior on the new doc-site scaffold dev branch.

#### What is your environment?

 Framework
- [ ] Angular
- [x] React
- [ ] Ionic
- [ ] React Native

#### Anything else to add?
This is caused by creating a new scroll container instead of letting the `window` object control the scroll. This will also cause other issues on mobile (momentum scrolling will not work except for window).

We may also need to remove overflow: scroll and replace it with overflow:auto wherever it's used to avoid showing the scrollbar when it is not necessary (i.e., Windows).

**Comment by emclaug2** [comment]
We had a fix for the sticky scrolling, but decided to omit it because there are more graceful solutions available to users.   React Router has an available solution found here: https://reacttraining.com/react-router/web/guides/scroll-restoration

There was a fix applied that made mobile scrolling hide the search bar.
