### ISSUE TITLE
InfoListItem not wrapped or clipped properly

### ISSUE THREAD

**Issue by huayunh** [pxblue/react-component-library#160]
#### Describe the bug
InfoListItem used to clip an overflowing text or wrap it, now the component doesn't do that. (default behavior is an overflow:hidden)

#### What is the expected behavior?
When there is a long text, either wrap the title or clip it with an ellipsis 

#### What are the steps to reproduce?
1. Go to storybook
2. shrink the canvas so that the text overflow
3. observe that the text just gets clipped off

#### Screenshots or links to minimum reproduction example
![image](https://user-images.githubusercontent.com/8997218/87327639-49623200-c502-11ea-9b6f-11ff98ecaff4.png)
from https://pxblue-components.github.io/react/?path=/story/components-info-list-item--with-right-component

#### Environment
Chrome on MacOS
		
#### Anything else to add?
wrapTitle & wrapSubtitle is still working just fine.

**Comment by joebochill** [comment]
This is an issue with the implementation of the third line of text. 
We need to use the noWrap prop on both the subtitle and info Typography elements within the secondaryText of the MuiListItem.
