### ISSUE TITLE
Use precommit to generate licenses

### ISSUE THREAD

**Issue by huayunh** [pxblue/react-component-library#168]
#### Describe the desired behavior

Use a precommit script to generate licenses, maybe prettier too

See how [react-auth-shared](https://github.com/pxblue/react-auth-shared/blob/dev/package.json) does it.

#### Describe the current behavior

It does not

#### Is this request related to a current issue?

NO

#### Other context
Maybe we can try this out for all the repos?

**Comment by huayunh** [comment]
(1) the `generate:licenses` stuff is not doing anything substantial, so I focused on incorporating the prettier & lint commands into a prepush hook
(2) I saw that in react-auth-shared, they are using `husky` for the hooks part. I tried but it does not work. It might be that the hook only works with `npm` but not `yarn`. I will mark this as won't fix for now...

**Comment by joebochill** [comment]
It doesn't need to be a hook, just a script in the package.json is how we're doing it everywhere else (run it manually before you push). I added the script in #186 but it doesn't do the licenses yet...should be an easy add.

**Comment by huayunh** [comment]
Write a new story to do `precommit` that run prettier, lint, license generating, etc.

**Comment by jeffvg** [comment]
moved to PXBLUE-1913
