### ISSUE TITLE
Storybook Drawer Stories Crash in Dev

### ISSUE THREAD

**Issue by emclaug2** [pxblue/react-component-library#169]
#### Describe the bug
Storybook Drawer Stories (react dev env) cause a crash when Dark mode is enabled.

#### What is the expected behavior?
Theme should switch without issues.

#### What are the steps to reproduce?
1. Go here:  https://pxblue-components.github.io/react-dev/?path=/story/components-drawer--with-basic-config
2. Toggle Dark Mode
3. Observe the Crash

#### Screenshots or links to minimum reproduction example
![image](https://user-images.githubusercontent.com/6538289/88709767-9d187200-d0e3-11ea-9c71-8247b5fb6ca6.png)

#### Environment
Chrome

**Comment by jeffvg** [comment]
![image](https://user-images.githubusercontent.com/37150565/88711218-d94cd200-d0e5-11ea-8b99-7e4095e3190c.png)
