### ISSUE TITLE
Add Dense drawer items

### ISSUE THREAD

**Issue by joebochill** [pxblue/react-component-library#183]
#### Describe the desired behavior
Should we be able to render an InfoListItem that is 48px tall in the drawer.

#### Describe the current behavior
Smallest option is using dense, which gives 52px tall.

#### Additional Context
Do this by utilizing the props and styles of the info list item and not make new variant of the info-list-item

**Comment by huayunh** [comment]
Note: on React, you can pass in something like `{style: {height: 48px}}` to the `InfoListItemProps` field of each individual drawer item, and you can do class overrides on Angular

But we can still add props / directives to our API

**Comment by huayunh** [comment]
I did a dirty PoV using showcase's drawer, with `InfoListItemProps` on each NavItem set to 48px height, and `classes={{active: classes.activeBackground}}` on `DrawerNavGroup`. Here's what it looks like:
![image](https://user-images.githubusercontent.com/8997218/103238084-9d799b00-4917-11eb-8a9a-bb69a777650e.png)

Do we still feel the need to supply the "denser" ILI version? Or shall this be handled inside drawer logics?

**Comment by jeffvg** [comment]
moved to PXBLUE-1912
