### ISSUE TITLE
Use generic typing for InfoListItemProps

### ISSUE THREAD

**Issue by huayunh** [pxblue/react-component-library#193]
## Describe the desired behavior

InfoListItemProps should be able to pass in any components with any types without needing to use ts-ignore, like 

```tsx
<InfoListItem 
    title={'asdf'}
    component={'a'}
    href={'asdf'}
/>
```
(href is an attribute of `<a>`, and info list item should be able to pick it up without needing a ts-ignore)

## Describe the current behavior

Currently we need a ts-ignore for href. In fact, if you try to do just 

```tsx
const InfoListItem: React.FC<ListItemProps> = (props) => <ListItem {...props} />
```
it will still flag you. So ListItem's `component` prop can only be in effect when you use it directly, but not via prop forwarding.

## Is this request related to a current issue?

https://github.com/pxblue/react-component-library/issues/182

Also see discussions from https://github.com/pxblue/react-component-library/pull/187

**Comment by joebochill** [comment]
See this part of the discussion on the PR about generic typing: https://github.com/pxblue/react-component-library/pull/187#issuecomment-686614216

We'll leave this as a lower priority item for now since we have a TS ignore workaround.

**Comment by jeffvg** [comment]
moved to PXBLUE-1911
