### ISSUE TITLE
Use recommended animation speeds for drawer

### ISSUE THREAD

**Issue by joebochill** [pxblue/react-component-library#210]
#### Describe the desired behavior
Use the recommended transition speeds for opening and closing the drawer (entering and exiting).

#### Describe the current behavior
Using the 'standard' speed for both in and out.

#### Is this request related to a current issue?
https://github.com/pxblue/react-component-library/pull/207#pullrequestreview-544130015

**Comment by huayunh** [comment]
In #214, we realized that `DrawerLayout` does not have a good enough way to tell whether a drawer is open or not. I tried using `padding===0` as the way to tell if a drawer is collapsed, only to unearth that persistent drawer would never get a `padding === 0`.

Perhaps one thing we can do is to implement some `useState` tricks and compare the padding values; if the padding appears to be shrinking, we say the drawer is collapsing and attach the necessary classes, and vice versa.
