### ISSUE TITLE
Class inheritance in the drawer is goofy

### ISSUE THREAD

**Issue by joebochill** [pxblue/react-component-library#221]
#### Describe the bug
The DrawerNavItem inherits `classes` from the DrawerNavGroup, but the classes used in the NavItem and the NavGroup are different. This can cause some unexpected behaviors or warnings in the console when trying to do class overrides.

#### What is the expected behavior?
I would like to see this refactored such that the DrawerNavGroup takes a `classes` prop of type DrawerNavGroupClasses, which only apply to the DrawerNavGroup itself. And then add a new prop to DrawerNavGroup (maybe another prop that can be passed in at the Drawer, DrawerBody, or DrawerNavGroup level) for `navItemClasses` that get passed down to all of the NavItem children.

#### Screenshots
NavGroup Classes and type:
![image](https://user-images.githubusercontent.com/29152776/104630223-83a2bc80-5668-11eb-8d32-914aae65e1a8.png)

NavItem classes:
![image](https://user-images.githubusercontent.com/29152776/104630290-9b7a4080-5668-11eb-8eba-298b3db6488b.png)

		
#### Anything else to add?
I think this is only an issue in the Drawer because of how we have implemented the prop/style inheritance through the component hierarchy, but it may be worth looking to make sure that there isn't a similar issue with any other components.

The types of DrawerRailItem and DrawerNavItem are also slightly different. The DrawerNavGroup `items` prop should be able to support either...this will probably need some typescript magic.

**Comment by joebochill** [comment]
Currently when you pass in a class to the DrawerNavGroup that exists on the DrawerRailItem for example, the style will work correctly, but you have to use a ts-ignore and the console will scream:
![image](https://user-images.githubusercontent.com/29152776/104632508-c914b900-566b-11eb-91a8-8b7375b3d177.png)

**Comment by emclaug2** [comment]
@joebochill Will most-likely fix this in his drawer refactor story.

**Comment by emclaug2** [comment]
👍
