### ISSUE TITLE
Ability to turn off tooltips on condensed Rail

### ISSUE THREAD

**Issue by joebochill** [pxblue/react-component-library#223]
#### Describe the desired behavior
I want to be able to enable/disable the tooltips that are applied to the condensed Rail Items.

#### Describe the current behavior
Currently they are on by default when the rail is condensed and cannot be turned off.

#### Is this request related to a current issue?
No.

#### Additional Context
This behavior matches the Angular implementation, so whatever we decide to do with it should be done in both frameworks

**Comment by emclaug2** [comment]
See what happens in angular if user doesn't provide a title for a condensed nav rail.

**Comment by daileytj** [comment]
@joebochill @emclaug2 If no title is passed in for a nav item there will be no tooltip shown for both angular and react component libraries. Do we want to have a specific prop that can be set to disable tooltips on demand even if a title is present or does not passing in a title satisfy the requirements here?

**Comment by huayunh** [comment]
If you want to go fancy about accessibility guidelines... 
WCAG has a level A requirement "If non-text content is a control or accepts user input, then it has a name that describes its purpose. " ([SC 1.1.1](https://www.w3.org/TR/UNDERSTANDING-WCAG20/text-equiv-all.html))
So yeah, I guess a title might still be desirable as an alt text or some aria label screen reader thing

If not, then I'd say not passing in a title would satisfy the requirement. I'd suggest adding a short sentence somewhere in the doc that describes this behavior.

**Comment by andrupu** [comment]
We can add a prop to show/hide tooltips.
