### ISSUE TITLE
User Menu title text change to 16px 600 weight

### ISSUE THREAD

**Issue by huayunh** [pxblue/react-component-library#225]
Studio Blue suggests that font size 16px works better for the spacing. 

Left: current; right: proposed
![image](https://user-images.githubusercontent.com/8997218/105071740-f9d16580-5a52-11eb-927c-74efaf931d87.png)

Drawer header remains unchanged at the moment

#### Additional Context
This will also apply to the Style of the react-native bottomsheet we would implement, if we ended up going for the bottom sheet route

**Comment by emclaug2** [comment]
Both angular and react User Menu are using DrawerHeader for header.  FYI.

**Comment by joebochill** [comment]
This was resolved in #247
