### ISSUE TITLE
Drawer Rail Active Font Weight may cause Line Break

### ISSUE THREAD

**Issue by emclaug2** [pxblue/react-component-library#227]
#### Describe the bug
When selecting a nav item in a rail, the active font weight may cause a line break if the text is too long.

#### What is the expected behavior?
Do not perform a line break.

#### Screenshots or links to minimum reproduction example
![rail-font-weight](https://user-images.githubusercontent.com/6538289/105366417-535d9f80-5bcd-11eb-89ca-b63d3ff40d81.gif)

#### Environment

Chrome Windows

**Comment by huayunh** [comment]
I guess we'd have to make everything font-weight 600, active or not active.

**Comment by jeffvg** [comment]
won't fix this issue. Not able to account for all items with text. Account for bold text that's too long.

**Comment by joebochill** [comment]
We won't fix this programatically. If you encounter this issue, consider changing your labels to something shorter to avoid the wrap.
