### ISSUE TITLE
Add a prop to delay the open on hover behavior of a persistent drawer

### ISSUE THREAD

**Issue by huayunh** [pxblue/react-component-library#232]
#### Describe the desired behavior

Add a prop `hoverDelay` (or whatever fits with MUI's naming tradition) so that the adopters can control the persistent drawer expand speed.

#### Describe the current behavior

We dictated the time to be 500ms [here](https://github.com/pxblue/react-component-library/blob/4cb2572049e93ef4140d92b290a0b0dc43f2f04c/components/src/core/Drawer/Drawer.tsx#L242).

#### Is this request related to a current issue?

No.

#### Additional Context
An adopter was mentioning to Ian that the users need to be very "skilled" to select the drawer item before it expands, and expressed some wish that it can be controlled through props / directives.

**Comment by jeffvg** [comment]
refer to angular storybook drawer example with full config.
