### ISSUE TITLE
Update Empty State description text color to black

### ISSUE THREAD

**Issue by joebochill** [pxblue/react-component-library#253]
#### Describe the desired behavior
Description text of the empty state color should be black (ask Huayun which value)

#### Describe the current behavior
Currently uses blue[500].

#### Is this request related to a current issue?
No

#### Additional Context

![image](https://user-images.githubusercontent.com/29152776/111875723-9344c700-8971-11eb-82f2-fb0561daa322.png)

**Comment by huayunh** [comment]
All the tweaks involved:

- Color of the large icon should be textSecondary on both light and dark themes
- Distance between button and description should be bumped up to 16 instead of 8
