### ISSUE TITLE
UserMenu menuGroups iconColor prop doesn't change the icon color

### ISSUE THREAD

**Issue by daileytj** [pxblue/react-component-library#305]
#### Describe the bug
The UserMenu menuGroups iconColor prop doesn't change the menu item icon color.

#### What is the expected behavior?
The UserMenu menuGroups iconColor prop should change the menu item iconColor.

#### What are the steps to reproduce?
1. Go to storybook and navigate to the UserMenu with custom colors story
2. Update the menu menugroups.iconColor prop via knobs
3. Observe icon color not changing

#### Screenshots or links to minimum reproduction example
![Screen Shot 2021-07-22 at 7 25 56 AM](https://user-images.githubusercontent.com/13989985/126640248-330965ac-002f-4421-b0e9-a4114672dbd5.png)
		
#### Anything else to add?
It looks like the component is accepting the menugroups.iconColor prop properly, then manually overwriting the color and setting it to `theme.palette.text.secondary`.

**Comment by emclaug2** [comment]
Make sure this issue does not happen in the React Native component library either.
