### ISSUE TITLE
NavGroup Props should be exposed at the Drawer/DrawerBody Level

### ISSUE THREAD

**Issue by joebochill** [pxblue/react-component-library#34]
#### Describe the desired behavior
Some of the props that would likely be applied across nav groups (e.g. chevron, expandIcon, activeColor, etc.) should be able to be set in one place.

#### Describe the current behavior
Currently these have to be set on each navGroup independently even . if the values are the same.

#### Is this request related to a current issue?
Identified as part of the nested drawer items work. Needed before 3.0.0

**Comment by huayunh** [comment]
PXBLUE-1165
