### ISSUE TITLE
UserMenu to support non-clickable items

### ISSUE THREAD

**Issue by emclaug2** [pxblue/react-component-library#38]
#### Describe the desired behavior
I want UserMenu to support non-clickable items.
If no onClick is passed to a UserMenuItem, cursor should be text and onClick should not dismiss the Menu.

#### Describe the current behavior
This was requested by Anjali who had a use-case of wanting a read-only row at the bottom of the menu.  
All UserMenu items have a cursor pointer and dismiss the Menu when clicked, even if there is no click event passed onto the item. 

#### Is this request related to a current issue?
No

**Comment by huayunh** [comment]
Note that as soon as I am finished with https://github.com/pxblue/react-component-library/tree/feature/inherit-props, one can do `onSelect: () => {}` to the nonclickable NavItem to disable the dismiss thing. Not an ideal solution though -- this will require a tweak on `InfoListItem`.
