### ISSUE TITLE
Look into when to use React node, React Element or JSX Element as types

### ISSUE THREAD

**Issue by huayunh** [pxblue/react-component-library#39]
#### Describe the desired behavior
Need a unified rule for when to use React node, React Element or JSX Element as return types & propTypes

#### Describe the current behavior
Nearly everything is JSX Element

https://github.com/pxblue/react-native-component-library/issues/15

**Comment by joebochill** [comment]
A `ReactElement` is an object with a type and props.
A `ReactNode` is a `ReactElement | ReactFragment | string | number | boolean | ReactNode[] | undefined | null`
A `JSX.Element` is a `ReactElement` that uses `<any,any>` for the props and type.

![image](https://user-images.githubusercontent.com/29152776/85601907-d2313080-b61c-11ea-964f-24dea668e70f.png)

https://stackoverflow.com/a/58123882

**Comment by joebochill** [comment]
Further, when we use `React.FC<props>` or `React.FunctionComponent<props>`, the interface for that is:
![image](https://user-images.githubusercontent.com/29152776/85602309-3d7b0280-b61d-11ea-858d-db1c1bce9b54.png)

**Comment by joebochill** [comment]
#### ReactElement vs. JSX.Element
Use ReactElement if you need to specify a specific props configuration for a return type
Use JSX.Element if you don't need to specify a specific prop configuration (or you don't care)

#### ReactNode
Use ReactNode if you want to support the additional types (besides a component), such as boolean, string, null, etc.
Only use this if you actually intend to support all of the types. If you just need null or undefined, you'd be better served by using `JSX.Element | null | undefined`

**Comment by huayunh** [comment]
Do we need to update any react/react-native components to standardize this?

**Comment by joebochill** [comment]
> Do we need to update any react/react-native components to standardize this?

I just made a PR with minor updates for React. I’ll be going through RN tomorrow.
