### ISSUE TITLE
DrawerLayout should manage responsive variants

### ISSUE THREAD

**Issue by joebochill** [pxblue/react-component-library#75]
#### Describe the desired behavior
DrawerLayout should be configurable to set a different drawer type at different breakpoints

#### Describe the current behavior
Switching the drawer variant has to be done at the drawer

#### Is this request related to a current issue?
No

#### Additional Context
We tried getting this to work before and it was a little janky. Seems easy enough to just put the logic on the drawer, but we may want to revisit this.
https://github.com/pxblue/react-component-library/pull/61

**Comment by joebochill** [comment]
We could change the variant prop to take a fixed string, or an object of breakpoints: e.g.,

```
<Drawer variant={'permanent'} />
// or
<Drawer variant={{
permanent: '>=100',
persistant: '>=200',
temporary: '<500'
}} />
```

**Comment by huayunh** [comment]
It is simpler right now that the user can specify the drawer variant on Drawer.
