### ISSUE TITLE
Add Ripple to Drawer NavItems and UserMenu Items

### ISSUE THREAD

**Issue by emclaug2** [pxblue/react-component-library#8]
#### Describe the desired behavior
Consult with Studio Blue to see if Ripple effect is desired on either Drawer Nav Items or User Menu Items.

#### Describe the current behavior
There is no ripple behavior.  
Drawer Nav Items and UserMenu Items both use the InfoListItem.

#### Is this request related to a current issue?
No

**Comment by joebochill** [comment]
@huayunh Did we discuss this with studio Blue or Kyle?

**Comment by huayunh** [comment]
Kyle said by default yes we need ripple effect but this can be optional
